### ISSUE TITLE
GSA代码

### ISSUE THREAD

**Issue by qdd1234** [Meituan-AutoML/Twins#5]
您好，我想问一下GSA代码在您的项目哪个部分可以找到？

**Comment by qdd1234** [comment]
作者您好，关于GSA我还有一个问题，GSA通过全局子采样然后将子采样得到的特征当作self-attention中的key，但是GSA具体做法是特征经过LSA之后进行GSA操作时仍然要将特征图分成m*n份，然后在每一份上进行self-attention，只不过将key替换为全局子采样得到的特征，是这样吗？

**Comment by cxxgtxy** [comment]
> 您好，我想问一下GSA代码在您的项目哪个部分可以找到？

line74 in gvt.py

**Comment by cxxgtxy** [comment]
> 作者您好，关于GSA我还有一个问题，GSA通过全局子采样然后将子采样得到的特征当作self-attention中的key，但是GSA具体做法是特征经过LSA之后进行GSA操作时仍然要将特征图分成m*n份，然后在每一份上进行self-attention，只不过将key替换为全局子采样得到的特征，是这样吗？

这只是一种实现的方式。GSA的关键在于对于每个组，通过某种方式生成一个key，这个key就代表整个组的信息，用于全局信息交互（与query进行score计算），在这一层中，所有的query都是与代表各组的key进行运算，从而可以获得global信息。
所以， GSA 并非在group内进行self attetion。LSA是在group内。
但在实际的实现时候，在feature map size很小的时候（比如stage3和4分别是14和7），这时候不能每组选一个代表，否则的话，stage4只有一个key，因此对于这种情况下，组代表的含义已经不是那么确切，而是subsample的key
PS：如果没有问题，这issue我就关掉了

**Comment by xiaohu2015** [comment]
@cxxgtxy 下面这种表述可能是不恰当的：

> Although the locally-grouped self-attention
mechanism is computation friendly, the image
is divided into non-overlapping sub-windows.
Thus, we need a mechanism to communicate between different sub-windows, as in Swin. Otherwise, the information would be always limited to
be processed locally and thus the receptive field
is only k1 × k2, which significantly degrades
the performance as shown in our experiments.
This resembles the fact that we cannot replace
all standard convolutions by depth-wise convolutions in CNNs.

对于每个stage，如果均采用一样的group attention，那么这个stage的感受野就是一直是k*k，但是由于存在金字塔结构，随着特征的downsample，那么感受野将k*(2 ** i)增加；我看到swin transformer 就算不采用shifted window，效果也还可以。

这里你类比 depth-wise convolutions，但是我觉得不太合适， depth-wise convolutions是卷积时输入是单channel，而不是全部的channel，好像和这里不是一个类似的东西。我觉得可能想表述的意思是采用kernel size为k，stride也为k的卷积吧？

**Comment by cxxgtxy** [comment]
1. 感谢指出。pyramid配置下，一直group attention,的确不会limit k*k，后面会修正这里的描述（让之前更严谨，论文之前的意思是当前stage的，并非返回原图）。我们做过只用LSA的ablation study，first row in Table8.效果有相对明显的降低。
PS回到原图情况下，如果只用group+下采样也会让信息无法充分交互。比如左上角的几个点，实际上几乎是永远local的，之所以用几乎，是因为下采样的时候，会对两个点（不同组）进行信息交互，而组内其他像素与别的组进行交互信息，这种机制是非常弱的。

2. 这里的类比是个不那么严谨的比喻。这里想描述的是不同组之间的信息交互，如果一直group下去，比较有限。

再次感谢，在下次版本中，我们会修正一下这里的描述。

**Comment by cxxgtxy** [comment]
没有问题的话，我关闭这个issue了。感谢大家对twins的关注。
